### ISSUE TITLE
Exporting private keys with MacOS doesn't work

### ISSUE THREAD

**Issue by miriamstreit** [chris2511/xca#530]
My MacOS version is Sonoma 14.2.1 and I'm using the xca version 2.5.0.

Currently none of the following ways to export a private key have worked for me:

- Exporting the private key directly under the tab "private keys" -> export: This will create an empty file, no matter which format I use.
- Exporting the private key under the tab "certificates" -> export -> export format "PEM + key": This will create a file containing the certificate but there is no key.

I am happy to provide a logfile if someone could point me to where it is located under MacOS.

**Comment by chris2511** [comment]
Issues #465 and #497 describe the "PEM +Key" issue, which is fixed in the upcoming release.
You may try [this latest action build](/chris2511/xca/actions/runs/8008895942)
Exporting the private key directly from the private keys tab always worked.
(Tested once more right now with 2.5.0 on Sonoma 4.2.1)

You are using the AppStore version or the DMG?

After setting the "Clipboard format" to PEM-private you could drag a key from XCA into the Finder to export it.

**Comment by GiladHi** [comment]
Hi Chris, any ETA for the upcoming release?

**Comment by chris2511** [comment]
> Hi Chris, any ETA for the upcoming release?

Very soon. This week if time permits.

**Comment by miriamstreit** [comment]
It is impossible for me to import the private key directly from my private key tab. My colleague is having exactly the same issues as me, he's also on Sonoma 14.2.1.

I downloaded the DMG from the website and installed it this way.

Could you please tell me how I can change the clipboard format? I was unable to find a setting like this.

Thank you so much!

**Comment by chris2511** [comment]
> Could you please tell me how I can change the clipboard format?

In the context menu of the "Private Keys" Tab: "Clipboard format" can be changed for all keys in this database.

> I tried the drag-and-drop approach without it which made xca crash.

This is fixed with xca-2.6.0, released yesterday and will export the public key only by default.

**Comment by miriamstreit** [comment]
Thank you! I found out that the format has already been set to "PEM Private". However, when I try to copy the key to my clipboard, xca still crashes. If I understood correctly, this functionality is working for you? There might be an issue with my installation or my database in this case. Where can I find the log file so we can troubleshoot this?

I have now installed the new version and tested all of the cases again:
- Drag-and-drop private key: xca freezes and does not respond anymore
- Copy private key to clipboard: xca freezes and does not respond anymore
- Export from side-menu in the tab private keys: still creates an empty file
- Export with certificate: now also creates an empty file, not even the certificate is there

xca 2.6.0 also crashes a lot more often than it did with the version 2.5.0. I had to force quit and restart it after every attempt because it just froze after I did something.

**Comment by chris2511** [comment]
Sounds very mysterious .... 
What CPU do you have?
On my M2 I cannot reproduce any of the reported crashes.

**Comment by miriamstreit** [comment]
I also have an M2 processor. It seems weird indeed.

I could also try some other ways of installation like Homebrew or the AppStore. Or do you think that doesn't matter? I'm asking because earlier you asked me how I installed xca. 

I asked my colleague to test these cases as well and for him xca 2.6.0 is installed in a language he doesn't understand. My previous installation was in English, my 2.6.0 installation is in German (which I don't mind as this is my native language). However there was no way to decide which language I want to install. This would probably go into another ticket as it is unrelated but I just wanted to let you know!

**Comment by rumpli** [comment]
I have the same database as miriamstreit and tried to export private keys as well:

- Drag-and-drop private key: Works for me on SOME keys. The only difference I see is the "source" of the key. It seems that "Generated" keys are working with this approach - "Imported" ones are not.
- Copy private key to clipboard: xca freezes and does not respond anymore (Application not responding) and has to be forced quit
- Export from side-menu in the tab private keys: xca freezes and does not respond anymore (Application not responding) and has to be forced quit - creates a zero byte file.
- Export with certificate in the side-menu in the certificate tab (PEM + key option): xca freezes and does not respond anymore (Application not responding) and has to be forced quit - creates a zero byte file.

I'm working on an "M2 Pro" MacBook Pro with Sonama 14.3.1

**Comment by chris2511** [comment]
https://github.com/chris2511/xca/releases/tag/RELEASE.2.7.0

**Comment by miriamstreit** [comment]
Just to add some feedback here as well: with version 2.8.0 (installed via dmg) and MacOS Sequoia 15.0.1 on a "M2 Max" MacBook Pro, I finally managed to export private keys successfully 🥳

**Comment by chris2511** [comment]
Thanks for verification
